- name: Commit result
  run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add playlist.m3u
    git diff --cached --quiet && echo "no changes" || git commit -m "update playlist"
    git push
